### PR TITLE
Build Erlang 27

### PR DESCRIPTION
**Pull request by arcusfelis**
Needed to run tests on Erlang 27 on circleci.
MIM-2251

### CODE REVIEW

**Comment by NelsonVides** [comment]
Do we want to update the underlying ubuntu version too? 24.04 was released a while back already :)

**Comment by arcusfelis** [comment]
this one https://hub.docker.com/layers/library/ubuntu/24.04/images/sha256-c920ba4cfca05503764b785c16b76d43c83a6df8d1ab107e7e6610000d94315c?context=explore?
last version is 22 days ago and 22.10 is still beta probably

**Comment by NelsonVides** [comment]
> this one https://hub.docker.com/layers/library/ubuntu/24.04/images/sha256-c920ba4cfca05503764b785c16b76d43c83a6df8d1ab107e7e6610000d94315c?context=explore? last version is 22 days ago and 22.10 is still beta probably

What do you mean by this? Ubuntu 24.04 is official and fully released 🤔

**Comment by arcusfelis** [comment]
uff, it is not underlying ubuntu version, it is cimg ubuntu, that's why tagging is weird.
I switched to current.

**Review by chrzaszcz — APPROVED** [review]
👍

**Pull request merged**
